@url = http://localhost:3001

POST {{url}}/user HTTP/1.1
Content-Type: application/json

{
    "nome":"braian",
    "email": "braian@braian",
    "senha": "eu"
}

###

POST {{url}}/userLogin HTTP/1.1
Content-Type: application/json

{
    "email":"braian@braian",
    "senha":"eu"
}

###

POST {{url}}/listEmail HTTP/1.1
Content-Type: application/json

{
    "email":"braian@braian"
}

### 

GET {{url}}/plotDash HTTP/1.1